//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareYourView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageTag
    {
        public int imageTag_ID { get; set; }
        public Nullable<int> image_ID { get; set; }
        public Nullable<int> tag_ID { get; set; }
    }
}
