//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareYourView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageMetadata
    {
        public int image_ID { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> capturedData { get; set; }
        public string capturedBy { get; set; }
    }
}
